name: Publish site
on:
  push:
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: sh build.sh
      - name: upload
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
      - name: deploy
        uses: actions/deploy-pages@v1
